CREATE DATABASE IF NOT EXISTS n2;
USE n2;

CREATE TABLE i(
 id INT AUTO_INCREMENT PRIMARY KEY,
 n VARCHAR(150)
);

CREATE TABLE c(
 id INT AUTO_INCREMENT PRIMARY KEY,
 n VARCHAR(150),
 i INT,
 FOREIGN KEY(i) REFERENCES i(id)
);

CREATE TABLE d(
 id INT AUTO_INCREMENT PRIMARY KEY,
 n VARCHAR(150),
 c INT,
 FOREIGN KEY(c) REFERENCES c(id)
);

CREATE TABLE t(
 id INT AUTO_INCREMENT PRIMARY KEY,
 n VARCHAR(50),
 a INT,
 s INT,
 d INT,
 FOREIGN KEY(d) REFERENCES d(id)
);

CREATE TABLE a(
 id INT AUTO_INCREMENT PRIMARY KEY,
 m VARCHAR(20),
 n VARCHAR(150)
);

CREATE TABLE atb(
 id INT AUTO_INCREMENT PRIMARY KEY,
 a INT,
 t INT,
 FOREIGN KEY(a) REFERENCES a(id),
 FOREIGN KEY(t) REFERENCES t(id)
);

CREATE TABLE mcomp(
 id INT AUTO_INCREMENT PRIMARY KEY,
 n VARCHAR(100),
 d INT,
 FOREIGN KEY(d) REFERENCES d(id)
);

CREATE TABLE nota(
 id INT AUTO_INCREMENT PRIMARY KEY,
 a INT,
 c INT,
 t INT,
 n DECIMAL(5,2),
 FOREIGN KEY(a) REFERENCES a(id),
 FOREIGN KEY(c) REFERENCES mcomp(id),
 FOREIGN KEY(t) REFERENCES t(id),
 UNIQUE(a,c,t)
);
